Repository tier4/aip_launcher, pull requests merged in 2025-08, with the labels that each got.

#497 feat: high resolution argument in lidar launch
  aip_common_sensor_launch/launch/hesai_OT128.launch.xml
  aip_common_sensor_launch/launch/nebula_node_container.launch.py
Labels: tag:run-build-and-test-differential

#525 feat(aip_common_sensor_launch, aip_xx1_gen2_launch): add packet_loss error_threshold and radar diagnostic parameters
  aip_common_sensor_launch/launch/hesai_OT128.launch.xml
  aip_common_sensor_launch/launch/nebula_node_container.launch.py
  aip_xx1_gen2_launch/config/ARS548.param.yaml
  aip_xx1_gen2_launch/config/lidar_gen2.yaml
  aip_xx1_gen2_launch/config/lidar_gen2_1.yaml
Labels: tag:run-build-and-test-differential

#529 chore(aip_x2_gen2_launch): enable sync diagnostics output for Nebula
  aip_x2_gen2_launch/config/ARS548.param.yaml
  aip_x2_gen2_launch/config/nebula_hesai_common.param.yaml
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#539 fix: dummy camera diag
  aip_x2_gen2_launch/config/dummy_diag_publisher/sensor_kit.param.yaml
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#542 chore(x2gen2): better CUDA pipeline
  aip_x2_gen2_launch/launch/lidar.launch.xml
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
  aip_x2_gen2_launch/launch/pointcloud_preprocessor.launch.py
Labels: backport tier4/universe, tag:run-build-and-test-differential
