Repository tier4/aip_launcher, pull requests merged in 2025-04, with the labels that each got.

#419 feat: rename to aip
  README.md
  aip_common_sensor_launch/CMakeLists.txt
  aip_common_sensor_launch/config/blockage_diagnostics.param.yaml
  aip_common_sensor_launch/config/distortion_corrector_node.param.yaml
  aip_common_sensor_launch/config/radar_tracks_msgs_converter.param.yaml
  aip_common_sensor_launch/config/radar_tracks_noise_filter.param.yaml
  aip_common_sensor_launch/config/ring_outlier_filter_node.param.yaml
  aip_common_sensor_launch/launch/ars408.launch.xml
  aip_common_sensor_launch/launch/gscam.launch.py
  aip_common_sensor_launch/launch/hesai_OT128.launch.xml
  aip_common_sensor_launch/launch/hesai_XT32.launch.xml
  aip_common_sensor_launch/launch/livox_horizon.launch.py
  aip_common_sensor_launch/launch/nebula_node_container.launch.py
  aip_common_sensor_launch/launch/new_livox_horizon.launch.py
  aip_common_sensor_launch/launch/spinnaker.launch.py
  aip_common_sensor_launch/launch/usb_cam.launch.py
  aip_common_sensor_launch/launch/velodyne_VLP16.launch.xml
  aip_common_sensor_launch/launch/velodyne_VLP32C.launch.xml
  aip_common_sensor_launch/launch/velodyne_VLS128.launch.xml
  aip_common_sensor_launch/package.xml
  aip_common_sensor_launch/scripts/septentrio_heading_converter.py
  aip_x1_launch/launch/lidar.launch.xml
  aip_x1_launch/package.xml
  aip_x2_gen2_launch/launch/gnss.launch.xml
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
  aip_x2_gen2_launch/package.xml
  aip_x2_launch/launch/radar.launch.xml
  aip_x2_launch/package.xml
  aip_xx1_gen2_launch/launch/gnss.launch.xml
  aip_xx1_gen2_launch/launch/lidar.launch.py
  aip_xx1_gen2_launch/launch/radar.launch.xml
  aip_xx1_gen2_launch/package.xml
  aip_xx1_launch/launch/lidar.launch.xml
  aip_xx1_launch/launch/radar.launch.xml
  aip_xx1_launch/package.xml
Labels: tag:run-build-and-test-differential

#416 feat: xx1 gen2 0.48 radar
  aip_xx1_gen2_launch/config/ARS548.param.yaml
  aip_xx1_gen2_launch/launch/ars548.launch.xml
  aip_xx1_gen2_launch/launch/radar.launch.xml
Labels: tag:run-build-and-test-differential

#421 chore: add argument of hires_mode for nebula
  aip_x2_gen2_launch/launch/lidar.launch.xml
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
Labels: tag:run-build-and-test-differential

#407 feat: read ntrip param env
  .cspell.json
  aip_x2_gen2_launch/launch/gnss.launch.xml
  aip_xx1_gen2_launch/launch/gnss.launch.xml
Labels: tag:run-build-and-test-differential

#428 chore(aip_x2_gen2_launch): use dual_return_filter for rear_upper LiDAR
  aip_x2_gen2_launch/launch/lidar.launch.xml
Labels: tag:run-build-and-test-differential, backport beta/x2/v0.41

#430 fix(aip_x2_gen2_description): move gnss to sensors_calibration.yaml
  aip_x2_gen2_description/config/sensor_kit_calibration.yaml
  aip_x2_gen2_description/config/sensors_calibration.yaml
Labels: tag:run-build-and-test-differential, backport beta/x2/v0.41, backport beta/x2/v0.29

#423 feat: apply agnocast
  aip_x2_gen2_launch/launch/lidar.launch.xml
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
  aip_x2_gen2_launch/launch/sensing.launch.xml
Labels: tag:run-build-and-test-differential, backport beta/x2/v0.41

#434 fix: modify timestamp offset
  aip_x1_launch/config/concatenate_and_time_sync_node.param.yaml
Labels: tag:run-build-and-test-differential

#436 feat: update senser interface for real vehicle
  aip_x1_description/config/sensor_kit_calibration.yaml
  aip_x1_description/package.xml
  aip_x1_description/urdf/sensor_kit.xacro
  aip_x1_launch/config/diagnostic_aggregator/sensor_kit.param.yaml
  aip_x1_launch/config/dummy_diag_publisher/sensor_kit.param.yaml
  aip_x1_launch/launch/imu.launch.xml
  aip_x1_launch/launch/lidar.launch.xml
Labels: tag:run-build-and-test-differential

#348 feat: acceleration and transport layer
  aip_common_sensor_launch/launch/hesai_OT128.launch.xml
  aip_common_sensor_launch/launch/hesai_XT32.launch.xml
  aip_common_sensor_launch/launch/nebula_node_container.launch.py
  aip_common_sensor_launch/launch/velodyne_VLP16.launch.xml
  aip_common_sensor_launch/launch/velodyne_VLP32C.launch.xml
  aip_common_sensor_launch/launch/velodyne_VLS128.launch.xml
  aip_xx1_launch/launch/lidar.launch.xml
  aip_xx1_launch/launch/pointcloud_preprocessor.launch.py
  aip_xx1_launch/package.xml
Labels: tag:run-build-and-test-differential

#438 feat(ring_outlier_filter): update parameters of ring outlier filter
  aip_common_sensor_launch/config/ring_outlier_filter_node.param.yaml
Labels: tag:run-build-and-test-differential

#437 feat: ip address setting for x1 lidar.
  aip_x1_launch/launch/lidar.launch.xml
Labels: tag:run-build-and-test-differential
