Repository tier4/aip_launcher, pull requests merged in 2025-09, with the labels that each got.

#557 feat(x2_gen2): polar voxel lidar for visibility
  aip_x2_gen2_launch/config/polar_voxel_outlier_filter_node.param.yaml
  aip_x2_gen2_launch/launch/lidar.launch.xml
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#558 feat: dummy diag update
  aip_x2_gen2_launch/config/dummy_diag_publisher/sensor_kit.param.yaml
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#560 feat(x2gen2): add cropbox around max steering extent of tires
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#564 dummy diag for visiblity validation
  aip_x2_gen2_launch/config/dummy_diag_publisher/sensor_kit.param.yaml
Labels: backport tier4/universe

#559 chore: imu bias scale corrector launch
  aip_x2_gen2_launch/config/gyro_bias_estimator.param.yaml
  aip_x2_gen2_launch/config/gyro_scale_estimator.param.yaml
  aip_x2_gen2_launch/launch/imu.launch.xml
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#581 chore(aip_x2_gen2_launch): rear_upper and right_lower FOV for lidar calibration
  aip_x2_gen2_launch/config/point_filters/rear_upper/full_for_calibration.param.png
  aip_x2_gen2_launch/config/point_filters/right_lower/full_for_calibration.param.png
Labels: tag:run-build-and-test-differential, backport beta/v0.41, backport beta/v0.48

#589 chore: adjust ring_outlier_filter
  aip_x2_gen2_launch/config/ring_outlier_filter_node.param.yaml
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#590 chore(nebula_node_container): change input topic to give better visibility results
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
Labels: tag:run-build-and-test-differential, backport beta/v0.48
