Repository tier4/aip_launcher, pull requests merged in 2025-05, with the labels that each got.

#442 chore(ring_outlier_filter): cherry pick#438
  common_sensor_launch/config/ring_outlier_filter_node.param.yaml
Labels: tag:run-build-and-test-differential

#443 chore(aip_x2_gen2_launch): move ring outlier filter param file to aip…
  aip_x2_gen2_launch/config/ring_outlier_filter_node.param.yaml
  aip_x2_gen2_launch/launch/lidar.launch.xml
Labels: tag:run-build-and-test-differential, backport beta/v0.41

#444 chore: merge beta/x2/v0.41 to beta/v0.41
  aip_x2_gen2_description/config/sensor_kit_calibration.yaml
  aip_x2_gen2_description/config/sensors_calibration.yaml
  aip_x2_gen2_launch/config/point_filters/front_lower/generated_30deg_roi.param.png
  aip_x2_gen2_launch/config/point_filters/front_upper/generated_30deg_roi.param.png
  aip_x2_gen2_launch/config/point_filters/left_lower/generated_30deg_roi.param.png
  aip_x2_gen2_launch/config/point_filters/left_upper/generated_30deg_roi.param.png
  aip_x2_gen2_launch/config/point_filters/rear_lower/generated_30deg_roi.param.png
  aip_x2_gen2_launch/config/point_filters/rear_upper/generated_30deg_roi.param.png
  aip_x2_gen2_launch/config/point_filters/right_lower/generated_30deg_roi.param.png
  aip_x2_gen2_launch/config/point_filters/right_upper/generated_30deg_roi.param.png
  aip_x2_gen2_launch/launch/lidar.launch.xml
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
  aip_x2_gen2_launch/launch/sensing.launch.xml
Labels: tag:run-build-and-test-differential

#448 feat(septentrio_heading_converter): handle NaN heading values
  aip_common_sensor_launch/scripts/septentrio_heading_converter.py
Labels: tag:run-build-and-test-differential

#447 chore(aip_x2_gen2_launch): update QT128 lidar min_range
  aip_x2_gen2_launch/launch/lidar.launch.xml
Labels: tag:run-build-and-test-differential

#446 feat(radar): update radar pipeline
  aip_x2_gen2_launch/config/ARS548.param.yaml
  aip_x2_gen2_launch/launch/radar.launch.xml
Labels: tag:run-build-and-test-differential

#457 feat(aip_x1_description): update x1 sensor config for new sensor_kit
  aip_x1_description/config/sensor_kit_calibration.yaml
  aip_x1_description/config/sensors_calibration.yaml
Labels: tag:run-build-and-test-differential, backport beta/x1/v2025.6
