Repository tier4/aip_launcher, pull requests merged in 2025-07, with the labels that each got.

#494 feat(aip_x2_gen2_launch): update config for radar diagnostics
  aip_x2_gen2_launch/config/ARS548.param.yaml
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#481 feat(aip_x2_gen2_launch): add simple tracked object merger configuration and launch integration
  aip_x2_gen2_launch/config/simple_tracked_object_merger.param.yaml
  aip_x2_gen2_launch/launch/radar.launch.xml
Labels: tag:run-build-and-test-differential

#500 chore(aip_x2_gen2_launch): is_main_ecu variable to use different imu
  aip_x2_gen2_launch/launch/imu.launch.xml
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#501 feat(aip_x2/xx1_gen2_launch): add simple tracked object merger configuration and launch integration (#481)
  aip_x2_gen2_launch/config/simple_tracked_object_merger.param.yaml
  aip_x2_gen2_launch/launch/radar.launch.xml
  aip_x2_gen2_launch/package.xml
  aip_xx1_gen2_launch/config/ARS548.param.yaml
  aip_xx1_gen2_launch/config/simple_tracked_object_merger.param.yaml
  aip_xx1_gen2_launch/launch/radar.launch.xml
  aip_xx1_gen2_launch/package.xml
Labels: tag:run-build-and-test-differential

#499 chore(aip_x2_gen2_description): move imu to sensor calibration
  aip_x2_gen2_description/config/sensor_kit_calibration.yaml
  aip_x2_gen2_description/config/sensors_calibration.yaml
  aip_x2_gen2_description/urdf/sensor_kit.xacro
  aip_x2_gen2_description/urdf/sensors.xacro
Labels: tag:run-build-and-test-differential, backport beta/v0.41, backport beta/v0.48

#510 fix(aip_x2_gen2_description): imu roll
  aip_x2_gen2_description/config/sensors_calibration.yaml
Labels: tag:run-build-and-test-differential, backport beta/x2/v0.29, backport beta/v0.41

#518 feat(x1): add nebula diagnostic parameters
  aip_common_sensor_launch/config/nebula_hesal_common.param.yaml
  aip_common_sensor_launch/launch/hesai_XT32.launch.xml
  aip_common_sensor_launch/launch/nebula_node_container.launch.py
  aip_x1_launch/launch/lidar.launch.xml
Labels: tag:run-build-and-test-differential

#478 feat(x2gen2): nebula Agnocast support
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
Labels: tag:run-build-and-test-differential, backport beta/v0.48

#521 fix: update file name
  aip_common_sensor_launch/config/nebula_hesai_common.param.yaml
Labels: tag:run-build-and-test-differential
