Repository tier4/aip_launcher, pull requests merged in 2025-06, with the labels that each got.

#461 feat: add paramter for diag message
  aip_common_sensor_launch/config/distortion_corrector_node.param.yaml
  aip_common_sensor_launch/config/ring_outlier_filter_node.param.yaml
  aip_common_sensor_launch/launch/nebula_node_container.launch.py
  aip_x2_gen2_launch/config/ring_outlier_filter_node.param.yaml
  aip_x2_gen2_launch/launch/nebula_node_container.launch.py
  aip_x2_launch/config/distortion_corrector_node.param.yaml
  aip_x2_launch/config/ring_outlier_filter_node.param.yaml
  aip_x2_launch/launch/pandar_node_container.launch.py
Labels: tag:run-build-and-test-differential

#474 chore(nebula_node_container): add hires_mode for OT128
  aip_common_sensor_launch/launch/nebula_node_container.launch.py
Labels: tag:run-build-and-test-differential

#475 chore(aip_x2_gen2_launch): reduce blockage_angle
  aip_x2_gen2_launch/launch/lidar.launch.xml
Labels: tag:run-build-and-test-differential, backport beta/v0.41

#467 feat(aip_xx1_gen2): enable CUDA-based pointcloud preprocessor
  aip_xx1_gen2_launch/launch/lidar.launch.py
Labels: backport tier4/universe

#482 chore(aip_x2_gen2_launch): add point_filters for lidar calibration
  aip_x2_gen2_launch/config/point_filters/front_lower/full_for_calibration.param.png
  aip_x2_gen2_launch/config/point_filters/front_upper/full_for_calibration.param.png
  aip_x2_gen2_launch/config/point_filters/left_lower/full_for_calibration.param.png
  aip_x2_gen2_launch/config/point_filters/left_upper/full_for_calibration.param.png
  aip_x2_gen2_launch/config/point_filters/rear_lower/full_for_calibration.param.png
  aip_x2_gen2_launch/config/point_filters/rear_upper/full_for_calibration.param.png
  aip_x2_gen2_launch/config/point_filters/right_lower/full_for_calibration.param.png
  aip_x2_gen2_launch/config/point_filters/right_upper/full_for_calibration.param.png
Labels: tag:run-build-and-test-differential, backport beta/v0.41
